-- 코드를 작성해주세요
SELECT B.YD, (B.MS - SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA A JOIN (
SELECT YEAR(DIFFERENTIATION_DATE) AS YD, MAX(SIZE_OF_COLONY) AS MS
FROM ECOLI_DATA
GROUP BY YD) B
WHERE YEAR(A.DIFFERENTIATION_DATE) = B.YD
ORDER BY B.YD, YEAR_DEV;